### ISSUE TITLE
Show blame for multiple lines

### ISSUE THREAD

**Issue by Tardog** [psykzz/st3-gitblame#15]
First, thank you for creating this handy plugin. I think it does its job very well already, but there is one feature I would really like to see: The ability to display blame information for more than one line.

Possible use cases:

* I want to display complete blame information for the current file, in order to get a quick overview on code history.
* I’m interested in who was the last one to touch a specific method. Instead of moving the cursor from line to line and invoking git blame for each one separately, I want to be able to select all of them and just hit the shortcut once.

**Comment by gh640** [comment]
I also want the multi-line function. I tried to make a PR :)
