### ISSUE TITLE
When calling from the same selection, hide the current blame

### ISSUE THREAD

**Issue by brentswisher** [psykzz/st3-gitblame#17]
First, thanks again for writing this, I had to go through a bunch of old code today and this made it way easier to see who/when things were added. The only thing I thought would be nice is if I could use the keyboard shortcut to toggle hiding the blame once I had read it. I took a shot at making the change myself, and it seems to be working for me. Its pretty much the first python I've ever written, so no hard feelings if something needs to change.

**Comment by psykzz** [comment]
Thanks, will release this in the next release!
