### ISSUE TITLE
BlameEraseAllCommand is run upon every keystroke in every view

### ISSUE THREAD

**Issue by frou** [psykzz/st3-gitblame#19]
This cannot be good for efficiency...!

**Comment by frou** [comment]
Ideally the `ViewEventListener` would only be attached during the time that the "all blame" phantoms are being shown?

cc @gh640

**Comment by gh640** [comment]
@frou thank you for sharing the issue! I'll investigate it when I have a time.

**Comment by gh640** [comment]
@frou Surely `BlameEraseAllCommand` is run on every change to view...

I tried introducing a new setting to views to make the command run only when "all blame" phantoms are displayed. I took this approach because it seems that we don't have a way to attach a `ViewEventListener` conditionally.

If possible, I'd like you to check the following PR:

https://github.com/psykzz/st3-gitblame/pull/20

Thanks 😃

**Comment by frou** [comment]
Greetings Hayato

Intuitively, this situation where code is run upon every keystroke in every view simply seems too heavyweight, regardless of whether that code early-outs (BlameEraseAllListener.on_modified)

Personally I don't know much about the Sublime API, but surely we can somehow find a way to make this fully conditional.

**Comment by gh640** [comment]
Hello Duncan.

Yeah, it's better to avoid unnecessary hook invocation if possible.

> Personally I don't know much about the Sublime API, but surely we can somehow find a way to make this fully conditional.

I don't think it's possible to make it fully conditional but the previous PR could be improved. I added a new commit :)

If you have a better idea, don't hesitate to go ahead beyond this PR!

**Comment by frou** [comment]
Great - thanks!

**Comment by gh640** [comment]
@frou Thank you, too!

@psykzz I'd like you to review the PR https://github.com/psykzz/st3-gitblame/pull/20 . This should bring a better performance for all GitBlame users :)

**Comment by psykzz** [comment]
Thanks for the work here guys, merged the PR and will release in a moment.

**Comment by gh640** [comment]
@psykzz thank you so much!
