### ISSUE TITLE
Feature request: copy commit id or copy git show commit_id

### ISSUE THREAD

**Issue by ahmedam55** [psykzz/st3-gitblame#3]
Thanks for your time and effort creating that awesome package.

I'd be cool if I can copy the commit id and even cooler if I can by click copy a whole git command like: `gitk commit_id` or `git show commit_id`

**Comment by psykzz** [comment]
Seems reasonable, I think just copying the sha should be ideal then you can use it with `git diff` and other commands.

Would that also work for you?

**Comment by psykzz** [comment]
@ahmedam55 Can you check out the PR and let me know if that works for you?

**Comment by brendon** [comment]
That's a great feature. I had to come here because I was confused that the blame just disappeared after I clicked the sha. What do you think about displaying 'Copied!' at the end and not hiding the blame. Kind of like how the github URL copier works.

**Comment by psykzz** [comment]
Can you create a new issue for it so I can track it ?
