### ISSUE TITLE
change highlighter color (feature)

### ISSUE THREAD

**Issue by Gaurav2728** [psykzz/st3-gitblame#5]
hi,

I am using git blame plugin with sublime text 3 and Primer.lighter Theme
https://packagecontrol.io/packages/Theme%20-%20Primer

when i use `git blame` the UI (commit) highlighter is horrible and can't view
![screen shot 2017-03-08 at 7 22 55 pm](https://cloud.githubusercontent.com/assets/1284716/23706639/083403ee-0435-11e7-86b0-14c039249248.png)

there is any way can i change highlighter text color.

**Comment by psykzz** [comment]
Oh yeah I see, i'll see if i can add a setting to flip the colours to a lighter theme instead.

Do you have a preference on colours that would work for you?

**Comment by Gaurav2728** [comment]
@psykzz  my sublime text 3 settings are:
```
{
	"auto_indent": true,
	"binary_file_patterns":
	[
		".DS_Store",
		".gitignore"
	],
	"color_scheme": "Packages/User/SublimeLinter/primer.light (SL).tmTheme",
	"font_size": 12,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_padding_bottom": 1,
	"line_padding_top": 1,
	"mid_line_tabs": false,
	"rulers":
	[
		70,
		80
	],
	"tab_size": 2,
	"theme": "Primer.sublime-theme",
	"theme_primer_sidebar_font_large": true,
	"theme_primer_sidebar_tree_large": true,
	"theme_primer_tab_active_purple": true,
	"theme_primer_tabs_font_normal": true,
	"translate_tabs_to_spaces": true,
	"use_tab_stops": true,
	"vintage_start_in_command_mode": false
}
```
It's light theme so you can chose any standard colour for light theme. 
But i think colours should have some configuration option so it can be change according to theme.
👍  for `i'll see if i can add a setting to flip the colours to a lighter theme instead.`

**Comment by psykzz** [comment]
@Gaurav2728 can you check #6 let me know what you think? I'll merge and release and you should see the change soon(tm)
