### ISSUE TITLE
Display notification when blame SHA has been copied

### ISSUE THREAD

**Issue by brendon** [psykzz/st3-gitblame#7]
I was confused that the blame just disappeared after I clicked the SHA. What do you think about displaying 'Copied!' at the end and not hiding the blame. Kind of like how the github URL copier works.

**Comment by psykzz** [comment]
Really like the idea, i just haven't had time to prioritize the work.
I'll add help-needed incase someone wants to help.

**Comment by brendon** [comment]
That's all good man. I've never used python before unfortunately and don't really have time to learn the ropes. I've already committed to learning some lua for another OS project :) Sorry I couldn't be of more help :)

**Comment by braver** [comment]
@brendon could you point me to the package for the "github URL copier"? It helps to have an example.

**Comment by brendon** [comment]
Thanks @braver! Sorry I was away overseas but I see you found it :D
